=== raml-apis/Twitch/schemas/object-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "_links" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "updated_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "user" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "_links" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "self" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "updated_at" : {
          "type" : "string" ,
          "required" : false
        } ,
        "logo" : {
          "type" : "string" ,
          "required" : false
        } ,
        "staff" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "display_name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "_id" : {
          "type" : "number" ,
          "required" : false
        } ,
        "created_at" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "_id" : {
      "type" : "number" ,
      "required" : false
    }
  }
}

=== raml-apis/Twitch/examples/object-example.json
{
  "_links" : {
    "self" : "https://api.twitch.tv/kraken/users/test_user1/blocks/test_user_troll"
  } ,
  "updated_at" : "2013-02-07T01:04:43Z" ,
  "user" : {
    "_links" : {
      "self" : "https://api.twitch.tv/kraken/users/test_user_troll"
    } ,
    "updated_at" : "2013-01-18T22:33:55Z" ,
    "logo" : "http://static-cdn.jtvnw.net/jtv_user_pictures/test_user_troll-profile_image-c3fa99f314dd9477-300x300.jpeg" ,
    "staff" : false ,
    "display_name" : "test_user_troll" ,
    "name" : "test_user_troll" ,
    "_id" : 22125774 ,
    "created_at" : "2011-05-01T14:50:12Z"
  } ,
  "_id" : 287813
}
