=== raml-apis/Twitch/schemas/team-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "_id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "created_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "info" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updated_at" : {
      "type" : "string" ,
      "required" : false
    } ,
    "background" : {
      "type" : "string" ,
      "required" : false
    } ,
    "banner" : {
      "type" : "string" ,
      "required" : false
    } ,
    "logo" : {
      "type" : "string" ,
      "required" : false
    } ,
    "_links" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "display_name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Twitch/examples/team-example.json
{
  "_id" : 2 ,
  "created_at" : "2011-10-11T23:59:43Z" ,
  "info" : "Team Info" ,
  "updated_at" : "2012-01-15T19:43:40Z" ,
  "background" : "http://static-cdn.jtvnw.net/jtv_user_pictures/team-eg-background_image-089a407eb59fe3b2.png" ,
  "banner" : "http://static-cdn.jtvnw.net/jtv_user_pictures/team-eg-banner_image-8089b058e6ffe4cd-640x125.png" ,
  "logo" : "http://static-cdn.jtvnw.net/jtv_user_pictures/team-eg-team_logo_image-53eaf029dad7d5c9-300x300.png" ,
  "_links" : {
    "self" : "https://api.twitch.tv/kraken/teams/eg"
  } ,
  "display_name" : "Evil Geniuses" ,
  "name" : "eg"
}
