=== raml-apis/Twitch/schemas/user-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "object",
  "properties": {
    "name": {
      "required": false,
      "type": "string"
    },
    "created_at": {
      "required": false,
      "type": "string"
    },
    "updated_at": {
      "required": false,
      "type": "string"
    },
    "_links": {
      "required": false,
      "type": "object",
      "properties": {
        "self": {
          "required": false,
          "type": "string"
        }
      }
    },
    "logo": {
      "required": false,
      "type": "string"
    },
    "_id": {
      "required": false,
      "type": "integer"
    },
    "display_name": {
      "required": false,
      "type": "string"
    },
    "email": {
      "required": false,
      "type": "string"
    },
    "partnered": {
      "required": false,
      "type": "boolean"
    }
  }
}

=== raml-apis/Twitch/examples/user-example.json
{
  "name" : "test_user1" ,
  "created_at" : "2011-06-03T17:49:19Z" ,
  "updated_at" : "2012-06-18T17:19:57Z" ,
  "_links" : {
    "self" : "https://api.twitch.tv/kraken/users/test_user1"
  } ,
  "logo" : "http://static-cdn.jtvnw.net/jtv_user_pictures/test_user1-profile_image-62e8318af864d6d7-300x300.jpeg" ,
  "_id" : 22761313 ,
  "display_name" : "test_user1" ,
  "email" : "asdf@asdf.com" ,
  "partnered" : true
}
